### ISSUE TITLE
[!] No podspec found for `pdf_viewer_jk` in `Flutter/.symlinks/pdf_viewer_jk/ios`

### ISSUE THREAD

**Issue by dochanhca** [jawadsahil/pdf_viewer_jk#1]
I'm getting this error when running project on iOS simulator. I tried run `flutter clean` but it's not working.

` 
CocoaPods' output:
↳
Preparing
Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter/engine`
    -> Fetching podspec for `FlutterPluginRegistrant` from `Flutter/FlutterPluginRegistrant`
    -> Fetching podspec for `contacts_service` from `Flutter/.symlinks/contacts_service/ios`
    -> Fetching podspec for `device_info` from `Flutter/.symlinks/device_info/ios`
    -> Fetching podspec for `fluttertoast` from `Flutter/.symlinks/fluttertoast/ios`
    -> Fetching podspec for `path_provider` from `Flutter/.symlinks/path_provider/ios`
    -> Fetching podspec for `path_provider_macos` from `Flutter/.symlinks/path_provider_macos/ios`
    -> Fetching podspec for `pdf_viewer_jk` from `Flutter/.symlinks/pdf_viewer_jk/ios`
    [!] No podspec found for `pdf_viewer_jk` in `Flutter/.symlinks/pdf_viewer_jk/ios`

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:901:in `fetch_external_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:880:in `block (2 levels) in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `block in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:878:in `fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
Error running pod install
Error launching application on iPhone 11 Pro Max. 
`

**Comment by jawadsahil** [comment]
I've done few changes.. Can you check with new version 0.0.3.. I have no access to all tools right now..

**Comment by dochanhca** [comment]
I updated to version 0.0.3. Now i getting another error:

`
Error output from Xcode build:
** BUILD FAILED **
Xcode's output:

    /Users/say-something/Downloads/development/flutter/.pub-cache/hosted/pub.dartlang.org/pdf_viewer_jk-0.0.3/ios/Classes/FlutterPluginPdfViewerPlugin.m:1:9: fatal error: 'FlutterPdfViewerPlugin.h' file not found
    #import "FlutterPdfViewerPlugin.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description
Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
`

**Comment by jawadsahil** [comment]
Sorry, that looks like the typo in file name. Please update to version 0.0.4.

**Comment by dochanhca** [comment]
Now I can build app normally. But I getting another error when tried to reading pdf file:

`
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Expanded(flex: 1):
The getter 'count' was called on null.
Receiver: null
Tried calling: count
`
I can read this pdf file well with some pdf plugin.
May be something error when try to get mumber of pages?

**Comment by jawadsahil** [comment]
Can you show me your code? this looks like you are not creating the document and it is null when you call the viewer. Did you try the code from example?

**Comment by dochanhca** [comment]
When my widget init, document is null. After loaded pdf file, i call setState() to update document. Maybe this make error happen?

**Comment by dochanhca** [comment]
Now I getting Expcetion when reading file
`
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Exception: Error reading PDF!
`

**Comment by jawadsahil** [comment]
This looks like the issue with your code. Or you have no access to your PDF file / or wrong path.
