### ISSUE TITLE
Exception caught by widgets library

### ISSUE THREAD

**Issue by NikhilKukreja26** [jawadsahil/pdf_viewer_jk#11]
Hello,
I am using pdf_viewer_jk: ^1.2.0 and i am getting the following error and i am using Flutter channel stable and Flutter version is 2.0.5
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4191 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
PDFViewer

Thank you :)

**Comment by jawadsahil** [comment]
This does not seem to be related to PDFViewer. Please check if this happens with latest version 2.1.0. Or provide some more details.

**Comment by NikhilKukreja26** [comment]
Thank you for your reply.
I will check with the new version and let you know.
Thank you :)

**Comment by NikhilKukreja26** [comment]
I am trying to load from asset also getting the same log which i mentioned above

**Comment by NikhilKukreja26** [comment]
Now it is started working on android i restarted the app it loaded the pdf from asset and also from url.
You can close the issue.
Thank you so much  and God bless you always :)
