### ISSUE TITLE
pdf_viewer_jk: 2.0.0-nullsafety stuck when click on pickpage button 

### ISSUE THREAD

**Issue by limsocheat** [jawadsahil/pdf_viewer_jk#12]
When clicked on pickPage button, the app stuck. 

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-04-22 at 14 30 58](https://user-images.githubusercontent.com/6656644/115674883-4c832c00-a378-11eb-886a-a2606d750f1a.png)

**Comment by jawadsahil** [comment]
Can you check whether the latest version 2.1.0 behaves the same??

**Comment by jawadsahil** [comment]
Closing.... Could not reproduce.....
