### ISSUE TITLE
bug on the plugin

### ISSUE THREAD

**Issue by maxTeste** [jawadsahil/pdf_viewer_jk#15]
hey,
so i'm using this plugin and works fine,
but when is showing the pdf there is on blue button on the bottom of the page, that shows a list of all pages.
but when i click on the button i cant select a page or either exit from that list.
is just form me?

**Comment by sanalkv** [comment]
it's a bug. I'm facing it too.

**Comment by jawadsahil** [comment]
Fixed in 2.1.4
