### ISSUE TITLE
bug plugin not working 

### ISSUE THREAD

**Issue by maxTeste** [jawadsahil/pdf_viewer_jk#16]
hi,
i'm using this plugin and out of nowhere the plugin stopped working and gives this error:

/opt/flutter/.pub-cache/hosted/pub.dartlang.org/pdf_viewer_jk-2.1.2/lib/src/document.dart:75:14: Error: The class 'File' is abstract and can't be instantiated.
      file = File("${dir.path}/file.pdf");
             ^^^^
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/pdf_viewer_jk-2.1.2/lib/src/document.dart:83:26: Error: Non-nullable variable 'file' must be assigned before it can be used.
    document._filePath = file.path;
                         ^^^^
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/pdf_viewer_jk-2.1.2/lib/src/document.dart:86:24: Error: Non-nullable variable 'file' must be assigned before it can be used.
          {'filePath': file.path, 'clearCacheDir': clearPreviewCache});
                       ^^^^

edit:
I also tested with the code that is in the github repository and gives the same problem

**Comment by WolfWeasel** [comment]
I have the same error on version 2.1.0. I upgraded from 2.0.0-nullsafety.

**Comment by thejundguy** [comment]
same error, any workaround? i'm on flutter 2.2.1

**Comment by jawadsahil** [comment]
What is your flutter , and dart version?

**Comment by souurz** [comment]
The error occurred after "pub upgrade". Latest version library:  pdf_viewer_jk: ^2.1.0
[✓] Flutter (Channel beta, 2.2.0, on Mac OS X 10.15.7 19H2 darwin-x64, locale ru-RU)
    • Flutter version 2.2.0
    • Framework revision b22742018b (3 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Platform android-S, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

**Comment by jawadsahil** [comment]
The bug arises after upgrade to Flutter 2.2. It was OK with Flutter 2.0. I will be publishing an update soon for Flutter 2.2.

**Comment by jawadsahil** [comment]
published pdf_viewer_jk-2.1.3.. Please upgrade.
