### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by LeiSoftware** [jawadsahil/pdf_viewer_jk#17]
I got exception when openning the PDF on android. It happens after the phone got update. The phone is Samsung S7 edge. the android version is 8.0.0. The Samsung Experience version  is 9.0. Android security patch level is 1 September 2020.

**Null check operator used on a null value**

    sliver_multi_box_adaptor.dart in RenderSliverMultiBoxAdaptor.childMainAxisPosition at line 567 within flutter
    sliver_multi_box_adaptor.dart in RenderSliverMultiBoxAdaptor.paint at line 635 within flutter
    object.dart in RenderObject._paintWithContext at line 2317 within flutter
    object.dart in PaintingContext.paintChild at line 187 within flutter
    sliver_padding.dart in RenderSliverEdgeInsetsPadding.paint at line 274 within flutter
    object.dart in RenderObject._paintWithContext at line 2317 within flutter
    object.dart in PaintingContext.paintChild at line 187 within flutter
    viewport.dart in RenderViewportBase._paintContents at line 654 within flutter
    object.dart in PaintingContext.pushLayer at line 394 within flutter
    object.dart in PaintingContext.pushClipRect at line 450 within flutter
    viewport.dart in RenderViewportBase.paint at line 635 within flutter
    object.dart in RenderObject._paintWithContext at line 2317 within flutter
    object.dart in PaintingContext._repaintCompositedChild at line 139 within flutter
    object.dart in PaintingContext.repaintCompositedChild at line 100 within flutter
    object.dart in PipelineOwner.flushPaint at line 975 within flutter
    binding.dart in RendererBinding.drawFrame at line 464 within flutter
    binding.dart in WidgetsBinding.drawFrame at line 876 within flutter
    binding.dart in RendererBinding._handlePersistentFrameCallback at line 328 within flutter
    binding.dart in SchedulerBinding._invokeFrameCallback at line 1144 within flutter
    binding.dart in SchedulerBinding.handleDrawFrame at line 1082 within flutter
    binding.dart in SchedulerBinding._handleDrawFrame at line 998 within flutter
    zone.dart in _rootRun at line 1354
    zone.dart in _CustomZone.run at line 1258
    zone.dart in _CustomZone.runGuarded at line 1162
    hooks.dart in _invoke at line 163
    platform_dispatcher.dart in PlatformDispatcher._drawFrame at line 259
    hooks.dart in _drawFrame at line 126

[✓] Flutter (Channel stable, 2.2.1, on macOS 11.2.3 20D91 darwin-x64, locale en-AU)
• Flutter version 2.2.1 at /Users/lli/flutter
• Framework revision 02c026b03c (9 days ago), 2021-05-27 12:24:44 -0700
• Engine revision 0fdb562ac8
• Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
• Android SDK at /Users/bravedev/Library/Android/sdk
• Platform android-29, build-tools 29.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 12.5, Build version 12E262
• CocoaPods version 1.10.1

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.23.0

[✓] Connected device (3 available)
• Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
• macOS (desktop) • macos • darwin-x64 • macOS 11.2.3 20D91 darwin-x64
• Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

**Comment by jawadsahil** [comment]
The error logs do not show anything related to this plugin.
