### ISSUE TITLE
Attempt to invoke virtual method 'android.content.res.Resources android.app.Activity.getResources()' on a null object reference

### ISSUE THREAD

**Issue by LeiSoftware** [jawadsahil/pdf_viewer_jk#18]
This is happening when run on android phone debugging in android studio on mac OS. 

**Attempt to invoke virtual method 'android.content.res.Resources android.app.Activity.getResources()' on a null object reference**

I/System.out(29578): Attempt to invoke virtual method 'android.content.res.Resources android.app.Activity.getResources()' on a null object reference
W/System.err(29578): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.app.Activity.getResources()' on a null object reference
W/System.err(29578): 	at pro.jawad.pdf_viewer_jk.PdfViewerJkPlugin.getPage(PdfViewerJkPlugin.java:168)
W/System.err(29578): 	at pro.jawad.pdf_viewer_jk.PdfViewerJkPlugin.access$100(PdfViewerJkPlugin.java:29)
W/System.err(29578): 	at pro.jawad.pdf_viewer_jk.PdfViewerJkPlugin$1.run(PdfViewerJkPlugin.java:70)
W/System.err(29578): 	at android.os.Handler.handleCallback(Handler.java:789)
W/System.err(29578): 	at android.os.Handler.dispatchMessage(Handler.java:98)
W/System.err(29578): 	at android.os.Looper.loop(Looper.java:164)
W/System.err(29578): 	at android.os.HandlerThread.run(HandlerThread.java:65)

[✓] Flutter (Channel stable, 2.2.1, on macOS 11.2.3 20D91 darwin-x64, locale en-AU)
    • Flutter version 2.2.1 at /Users/lli/flutter
    • Framework revision 02c026b03c (9 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/bravedev/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

**Comment by cool-lei** [comment]
Any plan to migrate the plugin to Flutter android embedding V2?

**Comment by LeiSoftware** [comment]
Found someone fixed same issue:

"
PdfViewerJkPlugin.java, error appear at line 157 and 158

**double width = instance.activity().getResources().getDisplayMetrics().densityDpi * page.getWidth();
double height = instance.activity().getResources().getDisplayMetrics().densityDpi * page.getHeight();**

I think there is some problem with activity, so i decided manually replaced it into

**double width = instance.context().getResources().getDisplayMetrics().densityDpi * page.getWidth();
double height = instance.context().getResources().getDisplayMetrics().densityDpi * page.getHeight();**

"

**Comment by jawadsahil** [comment]
Fixed in 2.1.4
