### ISSUE TITLE
XMLHttpRequest error on fetching pdf from url

### ISSUE THREAD

**Issue by gegobyte** [jawadsahil/pdf_viewer_jk#19]
I have a functional android app in which I fetch pdf from url and display the fetched pdf in app, now I am trying to make the same work for web. I have put the code to fetch the pdf from url in try catch like this:

```
if (kIsWeb) launch(pdfBillUrl);  
try {
      PDFDocument pdfDocument = await PDFDocument.fromURL(pdfBillUrl);
      ...
    } catch (error) {
      showDialog(
        context: context,
        builder: (context) {
          return AlertDialog(
            content: Text(error.toString()),
            actions: <Widget>[
              TextButton(
                child: const Text('OK'),
                onPressed: () => Navigator.of(context).pop(),
              )
            ],
          );
        },
      );
    }
```

I am able to successfully open the pdf in chrome by using the `url_launcher` package and using it before try block and it works but the catch block is still triggered regardless.

So I am displaying the error text and it says `XMLHttpRequest error`, in Chrome console, I can see

`Access to XMLHttpRequest at
<pdf_url> from origin 'http://localhost:49306' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by jawadsahil** [comment]
This is related to CORS policy of browser, please read about it and add required headers.
