### ISSUE TITLE
Props showNavigation not working

### ISSUE THREAD

**Issue by wesleytoshio** [jawadsahil/pdf_viewer_jk#2]
### showNavigation: false continues showing
```dart
PDFViewer(
              document: document,
              showNavigation: false,
              indicatorBackground: Colors.black,
              showPicker: false,
              indicatorText: Colors.white,
            )
```
![image](https://user-images.githubusercontent.com/7057737/77085024-80a25580-69de-11ea-81bb-042f20a6c7cd.png)

**Comment by jawadsahil** [comment]
The navigation is shown when the document has more than one page, even if you set **showNavigation** to false. If you need custom behaviour, just override the PDFViewer class.

**Comment by wesleytoshio** [comment]
is it possible to hide the Navigation Menu you created? it's damaging my design ... thanks for the support

**Comment by jawadsahil** [comment]
Please update to version 1.0.0 and check if the menu is hidden.
