### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by xarmatura** [jawadsahil/pdf_viewer_jk#22]
@jawadsahil  Because every version of flutter_test from sdk depends on async 2.6.1 and pdf_viewer_jk >=2.1.3 depends on async ^2.7.0, flutter_test from sdk is incompatible with pdf_viewer_jk >=2.1.3.

**Comment by jawadsahil** [comment]
You need to resolve the issue yourself. pdf_viewer_jk  already use a greater version of async. Use latest version of flutter_test or use an older version of pdf_viewer_jk .
