### ISSUE TITLE
Suggestions for improved this plugin

### ISSUE THREAD

**Issue by wesleytoshio** [jawadsahil/pdf_viewer_jk#3]
It could have callback functions to get the current page and the total pages ex:
**PDFViewerController**
currentPage,
totalPage,
goToLast(),
goToFirst(),
gotoPage(int number)

#### What do we gain by that?
the ability to create custom controls based on the design of the application....
___
Thank u for all, u have a nice plugin, sorry for bad english and nomenclatures :(

**Comment by jawadsahil** [comment]
To achieve the results you want, just inherit the class "PDFViewer" e.g. "YourPDFViewer extends PDFViewer", and use it instead.

As you see in example:

    @override
      Widget build(BuildContext context) {
        Scaffold(
            appBar: AppBar(
              title: Text('Example'),
            ),
            body: Center(
            child: _isLoading
                ? Center(child: CircularProgressIndicator())
                : YourPDFViewer(document: document)),    //Use YourPDFViewer instead of PDFViewer
        );
      }

you can get the total pages by
    
    document.count

Also, see the code in PDFViewer file to get an idea of how to create your own viewer.
