### ISSUE TITLE
 Error reading PDF!        at PDFDocument.fromAsset(document.dart:74)

### ISSUE THREAD

**Issue by AbanobElkomos** [jawadsahil/pdf_viewer_jk#6]
Non-fatal Exception: java.lang.Exception: Exception: Error reading PDF!
       at PDFDocument.fromAsset(document.dart:74)
       at _BookState.loadDocument(book.dart:53)

pdf reader not work and application stopped  and this error sent to firebase Crashlytics  from some mobiles as in  Honor 8X   but the most mobiles not give this error
 
my code is 
    PDFDocument doc = await PDFDocument.fromAsset('assets/pdf/book.pdf');

**Comment by jawadsahil** [comment]
This looks like issue with PDF file.
