### ISSUE TITLE
Dependence on flutter_svg: 0.17 causes error

### ISSUE THREAD

**Issue by kehindeegunjobi93** [jawadsahil/pdf_viewer_jk#7]
This plugin depends on advanced network image which in turn depends on flutter_svg (version 0.17). Flutter_svg has a bug unless its updated to 0.18

**Comment by jawadsahil** [comment]
This package depends on flutter_advanced_networkimage and flutter_advanced_networkimage depends on flutter_svg 0.17.0.

flutter_advanced_networkimage is archived and the owner of flutter_advanced_networkimage have to update the package, before I can be update the dependency.

**Comment by jawadsahil** [comment]
dependencies updated in version 1.2.0
